# Generated by Django 6.0.8 on 2026-08-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/imgs/products",
                verbose_name="photo",
            ),
        ),
    ]
