# Generated by Django 6.0.8 on 2026-08-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status_order_unique_quote_per_user"),
        ("products", "0002_alter_product_photo"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product"), name="unique_product_per_order"
            ),
        ),
    ]
