[project]
name = "cursodjango"
version = "0.1.0"
description = "Curso de Django de Platzi"
readme = "README.md"
authors = [
    { name = "Edson Galan", email = "edd.galan@hotmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
cursodjango = "cursodjango:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
