# Generated by Django 6.0.7 on 2026-08-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
